# Gopkg.toml for working with kubectl/client-go and Kubernetes 1.13.4

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "c27b913fddd1a6c480c229191a087698aa92f0b1"
  # version = "1.13.4"

[[override]]
  name = "k8s.io/apiserver"
  revision = "79427f02047f9189a75b8cdaadccaf65a126853e"
  # version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "d002e88f6236312f0289d9d1deab106751718ff0"
  # version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/component-base"
  # no tags exist for correct version
  revision = "1925c57e3358154fd54383773de0c0c7710a9196"

[[override]]
  name = "k8s.io/metrics"
  revision = "34472d076c304d1dc65b4dc115aebf99f202d06e"
  # version = "kubernetes-1.13.4"

[prune]
  go-tests = true
  unused-packages = true
